<?php
// module/Album/view/album/album/index.phtml:

//$title = 'Front';
//$this->headTitle($title);
?>
<br>
<br>
<h1><?= $this->escapeHtml($title) ?></h1>

<p>
<h4><?= $this->escapeHtml("AWS Services") ?></h4>
<a href="<?= $this->url('album', ['action' => 'view', 'id' => 'ec2']) ?>">EC2</a>
<a href="<?= $this->url('album', ['action' => 'view', 'id' => 'rds']) ?>">RDS</a>
<a href="<?= $this->url('album', ['action' => 'view', 'id' => 's3']) ?>">S3</a>
<a href="<?= $this->url('album', ['action' => 'view', 'id' => 'sqs']) ?>">SQS</a>
<a href="<?= $this->url('album', ['action' => 'view', 'id' => 'elasticache']) ?>">Elasticache</a>
</p>

<p>
<h4><?= $this->escapeHtml("Concerto Services") ?></h4>
<a href="<?= $this->url('album', ['action' => 'concerto_service', 'id' => 'cms']) ?>">CMS</a>
<a href="<?= $this->url('album', ['action' => 'concerto_service', 'id' => 'mds']) ?>">MDS</a>
<a href="<?= $this->url('album', ['action' => 'concerto_service', 'id' => 'concerto_api']) ?>">Concerto API</a>
<a href="<?= $this->url('album', ['action' => 'concerto_service', 'id' => 'content_registry']) ?>">Content Registry</a>
<a href="<?= $this->url('album', ['action' => 'concerto_service', 'id' => 'apps_web']) ?>">Apps Web</a>
<a href="<?= $this->url('album', ['action' => 'concerto_service', 'id' => 'mongodb']) ?>">MongoDB</a>
<a href="<?= $this->url('album', ['action' => 'concerto_service', 'id' => 'watchtower']) ?>">Watchtower</a>
</p>