<?php
// module/Album/view/album/album/index.phtml:

$title = $id;
$this->headTitle($title);
?>

<h1><?= $this->escapeHtml($title) ?></h1>

<?php if ($albums->ec2) : ?>
    <table class="table">
        <tr>
            <th>Name</th>
            <th>JSON</th>
            <th>&nbsp;</th>
        </tr>
        <!--    --><?php //foreach ($albums as $album) : ?>
        <tr>
            <td><?= $this->escapeHtml("EC2") ?></td>
            <td><?= $this->escapeHtml($albums->ec2) ?></td>
        </tr>
        <!--    --><?php //endforeach; ?>
</table>
<?php endif; ?>


<?php if ($albums->rds) : ?>
    <table class="table">
        <tr>
            <th>Name</th>
            <th>JSON</th>
            <th>&nbsp;</th>
        </tr>
        <!--    --><?php //foreach ($albums as $album) : ?>
        <tr>
            <td><?= $this->escapeHtml("RDS") ?></td>
            <td><?= $this->escapeHtml($albums->rds) ?></td>
        </tr>
        <!--    --><?php //endforeach; ?>
    </table>
<?php endif; ?>


<?php if ($albums->s3) : ?>
    <table class= "table">
        <tr>
            <th>Name</th>
            <th>JSON</th>
        </tr>
        <tr>
            <td><?= $this->escapeHtml("S3") ?></td>
            <td><?= $this->escapeHtml($albums->s3) ?></td>
        </tr>
    </table>
<?php endif; ?>


<?php if ($albums->sqs) : ?>
    <table class= "table">
        <tr>
            <th>Name</th>
            <th>JSON</th>
        </tr>
        <tr>
            <td><?= $this->escapeHtml("SQS") ?></td>
            <td><?= $this->escapeHtml($albums->sqs) ?></td>
        </tr>
    </table>
<?php endif; ?>