<?php
// module/Album/view/album/album/index.phtml:

$title = $id;
$this->headTitle($title);
?>

<h1><?= $this->escapeHtml($title) ?></h1>


<?php if ($albums->ec2) : ?>
    <table class= table border="1">
        <tr>
            <?php foreach ($albums->ec2[0] as $key => $val) : ?>
                <th> <?= $key ?></th>
            <?php endforeach ?>
        </tr>

        <?php foreach ($albums->ec2 as $object => $instance) : ?>
            <tr>
            <?php foreach ($instance as $key => $val) : ?>
                <td> <?= $val ?> </td>
            <?php endforeach ?>
            </tr>
        <?php endforeach ?>
    </table>
<?php endif; ?>



<?php if ($albums->rds) : ?>
    <table class= table border="1">
        <tr>
            <?php foreach ($albums->rds[0] as $key => $val) : ?>
                <th> <?= $key ?></th>
            <?php endforeach ?>
        </tr>

        <?php foreach ($albums->rds as $object => $instance) : ?>
            <tr>
                <?php foreach ($instance as $key => $val) : ?>
                    <td> <?= $val ?> </td>
                <?php endforeach ?>
            </tr>
        <?php endforeach ?>
    </table>
<?php endif; ?>



<?php if ($albums->s3) : ?>
    <?php foreach ($albums->s3 as $val) : ?>
        <ul>
            <li><?= $val ?></li>
        </ul>
    <?php endforeach ?>
<?php endif; ?>


<?php if ($albums->sqs) : ?>
    <?php foreach ($albums->sqs->QueueUrls as $url) : ?>
        <ul>
            <li><?= $url ?></li>
        </ul>
    <?php endforeach ?>
<?php endif; ?>


<?php if ($albums->elasticache) : ?>
    <table class= table border="1">
        <tr>
            <?php foreach ($albums->elasticache[0] as $key => $val) : ?>
                <th> <?= $key ?></th>
            <?php endforeach ?>
        </tr>

        <?php foreach ($albums->elasticache as $object => $instance) : ?>
            <tr>
                <?php foreach ($instance as $key => $val) : ?>
                    <td> <?= $val ?> </td>
                <?php endforeach ?>
            </tr>
        <?php endforeach ?>
    </table>
<?php endif; ?>



