<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Application Dashboard POC')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('album') ?>">
                        <img src="<?= $this->basePath('img/zf-logo-mark.svg') ?>" height="28" alt="Zend Framework <?= \Application\Module::VERSION ?>"/>&nbsp;Application Dashboard POC
                    </a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?= $this->url('album', ['action' => 'view', 'id' => 'ec2']) ?>">EC2</a></li>
                        <li class="active"><a href="<?= $this->url('album', ['action' => 'view', 'id' => 'rds']) ?>">RDS</a></li>
                        <li class="active"><a href="<?= $this->url('album', ['action' => 'view', 'id' => 's3']) ?>">S3</a></li>
                        <li class="active"><a href="<?= $this->url('album', ['action' => 'view', 'id' => 'sqs']) ?>">SQS</a></li>
                        <li class="active"><a href="<?= $this->url('album', ['action' => 'view', 'id' => 'elasticache']) ?>">Elasticache</a></li>
                    </ul>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?= $this->url('album', ['action' => 'view', 'id' => 'cms']) ?>">CMS</a></li>
                        <li class="active"><a href="<?= $this->url('album', ['action' => 'view', 'id' => 'mds']) ?>">MDS</a></li>
                        <li class="active"><a href="<?= $this->url('album', ['action' => 'view', 'id' => 'concerto_api']) ?>">Concerto API</a></li>
                        <li class="active"><a href="<?= $this->url('album', ['action' => 'view', 'id' => 'content_registry']) ?>">Content Registry</a></li>
                        <li class="active"><a href="<?= $this->url('album', ['action' => 'view', 'id' => 'apps_web']) ?>">Apps Web</a></li>
                        <li class="active"><a href="<?= $this->url('album', ['action' => 'view', 'id' => 'mongodb']) ?>">MongoDB</a></li>
                        <li class="active"><a href="<?= $this->url('album', ['action' => 'view', 'id' => 'watchtower']) ?>">Watchtower</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            <?= $this->content ?>
            <hr>
            <footer>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
